web:
# web-path: /usr/local/project/bxm/
 web-path: E:/代码生成/bxm/src/main/resources/
bxm:
 project: http://demo.k.com
spring:
 http: 
  multipart:
   max-file-size : 1024Mb
   max-request-size : 2048Mb
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.8.211:3306/bxm?useUnicode=true&characterEncoding=utf-8
  username: root
  password: root
  filters: stat,wall,log4j
  maxActive: 20
  initialSize: 5
  maxWait: 60000
  minIdle: 1
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: select 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxOpenPreparedStatements: 20
  connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
  resources:
   static-locations:
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - classpath:/file/
    - file:${web.web-path}
   
logging :
  level : 
   root : info
   
server:
 port : 80
 context-path : /
 
mybatis-plus:
# 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
# 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/**/mapper/*Mapper.xml
#  mapper-locations: classpath:/cn/kiway/wx/reply/mapper/*Mapper.xml
#实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.kiway.**.entity
#com.yourpackage.*.entity
  global-config:
  #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: false
    #刷新mapper 调试神器
    refresh-mapper: true
    #刷新mapper 调试神器
    isRefresh: true
    #数据库大写下划线转换
    capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
#    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'